// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WalletComponent.Repositorys.EF;

namespace WalletComponent.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20181019094712_InitAzureDB01")]
    partial class InitAzureDB01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WalletComponent.Domains.ChatMessages", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("From");

                    b.Property<string>("Message");

                    b.Property<string>("To");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("WalletComponent.Domains.FriendNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Description");

                    b.Property<Guid>("FromUserId");

                    b.Property<string>("Message");

                    b.Property<int>("State");

                    b.Property<Guid>("ToUserId");

                    b.Property<DateTime>("UpdateTime");

                    b.HasKey("Id");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ToUserId");

                    b.ToTable("FriendNotification");
                });

            modelBuilder.Entity("WalletComponent.Domains.Groups", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Description");

                    b.Property<string>("GroupName");

                    b.Property<DateTime>("UpdateTime");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("WalletComponent.Domains.UserGroupRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("GroupId");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("UserGroupRelationship");
                });

            modelBuilder.Entity("WalletComponent.Domains.Users", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Description");

                    b.Property<string>("FullName");

                    b.Property<string>("HeadImg");

                    b.Property<string>("IdCard");

                    b.Property<string>("Mobile");

                    b.Property<string>("NickName");

                    b.Property<string>("PassWord");

                    b.Property<bool>("Sex");

                    b.Property<DateTime>("UpdateTime");

                    b.Property<string>("UserCode");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WalletComponent.Domains.FriendNotification", b =>
                {
                    b.HasOne("WalletComponent.Domains.Users", "FromUser")
                        .WithMany("FriendNotificationListByFrom")
                        .HasForeignKey("FromUserId");

                    b.HasOne("WalletComponent.Domains.Users", "ToUser")
                        .WithMany("FriendNotificationListByTo")
                        .HasForeignKey("ToUserId");
                });

            modelBuilder.Entity("WalletComponent.Domains.Groups", b =>
                {
                    b.HasOne("WalletComponent.Domains.Users", "User")
                        .WithMany("GroupList")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("WalletComponent.Domains.UserGroupRelationship", b =>
                {
                    b.HasOne("WalletComponent.Domains.Groups", "Group")
                        .WithMany("UserGroupRelationship")
                        .HasForeignKey("GroupId");

                    b.HasOne("WalletComponent.Domains.Users", "Users")
                        .WithMany("UserGroupRelationshipList")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
